#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_HOME=$(cd "${0%/*}" && pwd -P) || exit

if [ -z "${GRADLE_USER_HOME:-}" ] ; then
  if [ -d "$HOME/.codex/memories" ] ; then
    GRADLE_USER_HOME="$HOME/.codex/memories/gradle-user-home"
  else
    GRADLE_USER_HOME="$APP_HOME/.gradle-user-home"
  fi
  export GRADLE_USER_HOME
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "$JAVA_HOME" ] ; then
  JAVA_EXE=$JAVA_HOME/bin/java
else
  JAVA_EXE=java
fi

exec "$JAVA_EXE" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
